[package]
name = "nanite-factory-game-map"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["server"]

[[bin]]
name = "client"
path = "src/bin/client.rs"
required-features = ["client"]

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.18.1" }
bevy_ecs_tilemap = { version = "0.18.0", optional = true }
bevy_pancam = { version = "0.20.0", optional = true }
bevy_quick_response = { version = "0.6.0", optional = true }
crossbeam-channel = { version = "0.5.14" }
thiserror = { version = "2.0.18" }
bevy_tweening = { version = "0.15.0", optional = true }
wasm-bindgen = { version = "0.2.114", optional = true }
serde = { version = "1.0.219"}
serde-wasm-bindgen = { version = "0.6.5", optional = true }
anyhow = { version = "1.0.102" }
tracing-wasm = { version = "0.2.1", optional = true }
bevy_aseprite_ultra = { git = "https://github.com/Lommix/bevy_aseprite_ultra.git", rev = "6a3d5b7891670e8a77091101a80fcfc0d2476e22", optional = true }
wasm-bindgen-futures = { version = "0.4.50", optional = true }
ldtk_rust = { git = "https://github.com/daniel-brenot/ldtk_rust.git", features = ["bevy"], optional = true }
serde_json = { version = "1.0.140" }
bevy-inspector-egui = { version = "0.36.0", optional = true }
strum = { version = "0.27.2", features = ["derive"]}
cfg-if = { version = "1.0.4"}
ewebsock = {version = "0.8.0", features = ["tls"]}
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
wasm_result = { path = "wasm_result" }
rustls = { version = "0.23.37", features = ["ring"] }
lightyear = "0.26.4"
bimap = { version = "0.6.3", features = ["serde"] }


[features]
default = ["server", "client"]
server = ["lightyear/server", "lightyear/netcode", "lightyear/webtransport"]
client = [
    "atlas",
    "render",
    "bevy_ecs_tilemap",
    "bevy_pancam",
    "bevy_quick_response",
    "bevy_tweening",
    "wasm-bindgen",
    "serde-wasm-bindgen",
    "tracing-wasm",
    "bevy_aseprite_ultra",
    "wasm-bindgen-futures",
    "ldtk_rust",
    "bevy-inspector-egui"
]
atlas = ["bevy_ecs_tilemap/atlas"]
render = ["bevy_ecs_tilemap/render"]

# Hold your breath, this is a big one
[profile.release]
lto="fat"
codegen-units = 1
overflow-checks = false
incremental = false
debug=0
strip = "debuginfo"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
# wasm-opt = [
#     "-O4",
#     "--one-caller-inline-max-function-size",
#     "255",
#     "--inline-functions-with-loops",
#     "--ignore-implicit-traps",
#     "--traps-never-happen",
#     "--low-memory-unused",
#     "--fast-math",
#     "--zero-filled-memory",
#     "--flexible-inline-max-function-size",
#     "255",
#     ]
